---
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

name: Website-Test
title: Website Test
description: Test website for a Jekyll Blog
meta_description: Jekyll template, Medium styled, free for bloggers.
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: "/Website-Test"

markdown: kramdown
highlighter: rouge
