backend:
  name: github
  repo: mountainstorm/Website-Test
  branch: master # Branch to update (optional; defaults to master)
  base_url: http://localhost:5000/

media_folder: "assets/images"
public_folder: "Website-Test/assets/images"

display_url: https://mountainstorm.github.io/Website-Test/
logo_url: https://mountainstorm.github.io/Website-Test/assets/images/logo.png

collections:
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

editor:
   preview: false
